In [ ]:
#Function- reusbale block of code
#parameter:input for a function
#return value: output
#error handling: preventing code to fail
#readable code:naming, spacing, comments , simple structure. Making sure that the LOC is readable per function

In [1]:
#codeblock1
marks= [78,91,62]
avg = sum(marks)/ len(marks)
print(avg)

77.0


In [2]:
#codeblock2
def calculate_average(marks):
  return sum(marks)/ len(marks)

student_marks= [78,91,62]
average = calculate_average(student_marks)
print(average)

77.0


In [ ]:
#write a small pass/ fail function where it will print pass for greater than or equal to 27 warna fail

85

21

def check(marks):
  if marks>=26:
    print("Pass")
  else:
    print("Fail")
check(85)
check(21)

In [ ]:
#Python List
1.General purpose
2


#Numpy Array
1. numerical data focused only

In [3]:
marks= [78,91,62]
print (marks+10)

TypeError: can only concatenate list (not "int") to list

In [4]:
import numpy as np

marks_array= np.array([78,91,62])
print (marks_array+10)

[ 88 101  72]


In [ ]:
#3 main segments

#shape: structure of the array
#index: the position of an element in an array
#axis: direction

In [5]:
import numpy as np

arr = np.array([10, 20, 30, 40])
print(arr)
print(arr.shape)


matrix= np.array([
    [10,20,30],
    [40, 50, 60]
])
print(matrix)
print(matrix.shape)

[10 20 30 40]
(4,)
[[10 20 30]
 [40 50 60]]
(2, 3)


In [11]:
#indexing and slicing

grid = np.array([
    [11, 12, 13, 14, 15],
    [21, 22, 23, 24, 25],
    [31, 32, 33, 34, 35],
    [41, 42, 43, 44, 45],
    [51, 52, 53, 54, 55]
])

print(grid[0, 0])
print(grid[2, 3])
print(grid[4,3])
print(grid[0, :])
print(grid[:, 0])
print(grid[1:4,1:])

11
34
54
[11 12 13 14 15]
[11 21 31 41 51]
[[22 23 24 25]
 [32 33 34 35]
 [42 43 44 45]]


In [14]:
marks = np.array([78, 91, 55, 72, 40, 88])

print(marks>70)


high_scores= marks[marks >70]
print(high_scores)

#1.less than 60, print those marks

#2. greater and equal to 60 and less than equal to 90 print
#& and

[ True  True False  True False  True]
[78 91 72 88]


In [16]:
#basic numpy stats

marks = np.array([78, 91, 55, 72, 40, 88])

print(marks.min())
print(marks.max())
print(marks.mean())
print(marks.sum())


40
91
70.66666666666667
424


In [17]:
from google.colab import files
uploaded= files.upload()

Saving session4_dummy_students_data.csv to session4_dummy_students_data.csv


In [19]:
import pandas as pd

df=pd.read_csv("session4_dummy_students_data.csv")
print(df)

    student_id    name  age     city  math  science  english  \
0          101   Aarav   16   Mumbai    78       84       69   
1          102    Diya   16    Delhi    91       88       94   
2          103   Kabir   17  Mathura    55       61       58   
3          104   Meera   16    Noida    72       79       81   
4          105   Rohan   17   Mumbai    40       52       47   
5          106    Sara   16    Delhi    88       93       90   
6          107  Ishaan   17  Mathura    64       70       66   
7          108  Ananya   16    Noida    95       92       89   
8          109  Vivaan   17   Mumbai    48       57       51   
9          110    Tara   16    Delhi    83       76       85   
10         111   Arjun   17  Mathura    67       63       72   
11         112   Nisha   16    Noida    74       81       79   
12         113     Dev   17   Mumbai    35       45       42   
13         114   Priya   16    Delhi    89       86       91   
14         115   Kunal   17  Mathura    

In [20]:
print(df.head())

   student_id   name  age     city  math  science  english  \
0         101  Aarav   16   Mumbai    78       84       69   
1         102   Diya   16    Delhi    91       88       94   
2         103  Kabir   17  Mathura    55       61       58   
3         104  Meera   16    Noida    72       79       81   
4         105  Rohan   17   Mumbai    40       52       47   

   attendance_percent  study_hours_per_week  assignments_submitted  \
0                  92                     8                      9   
1                  96                    11                     10   
2                  75                     5                      6   
3                  89                     7                      8   
4                  68                     3                      5   

   final_project_score  
0                   82  
1                   93  
2                   60  
3                   78  
4                   45  


In [21]:
print(df.columns)

Index(['student_id', 'name', 'age', 'city', 'math', 'science', 'english',
       'attendance_percent', 'study_hours_per_week', 'assignments_submitted',
       'final_project_score'],
      dtype='object')


In [22]:
print(df.shape)

(20, 11)


In [23]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   student_id             20 non-null     int64 
 1   name                   20 non-null     object
 2   age                    20 non-null     int64 
 3   city                   20 non-null     object
 4   math                   20 non-null     int64 
 5   science                20 non-null     int64 
 6   english                20 non-null     int64 
 7   attendance_percent     20 non-null     int64 
 8   study_hours_per_week   20 non-null     int64 
 9   assignments_submitted  20 non-null     int64 
 10  final_project_score    20 non-null     int64 
dtypes: int64(9), object(2)
memory usage: 1.8+ KB
None


In [24]:
math_scores = df["math"].to_numpy()
print(math_scores)
print(type(math_scores))
print(math_scores.mean())


[78 91 55 72 40 88 64 95 48 83 67 74 35 89 58 92 61 80 43 77]
<class 'numpy.ndarray'>
69.5


In [25]:
df["average"] = df[["math","science", "english"]].mean(axis=1)
print(df[["name", "math", "science", "english", "average"]])

      name  math  science  english    average
0    Aarav    78       84       69  77.000000
1     Diya    91       88       94  91.000000
2    Kabir    55       61       58  58.000000
3    Meera    72       79       81  77.333333
4    Rohan    40       52       47  46.333333
5     Sara    88       93       90  90.333333
6   Ishaan    64       70       66  66.666667
7   Ananya    95       92       89  92.000000
8   Vivaan    48       57       51  52.000000
9     Tara    83       76       85  81.333333
10   Arjun    67       63       72  67.333333
11   Nisha    74       81       79  78.000000
12     Dev    35       45       42  40.666667
13   Priya    89       86       91  88.666667
14   Kunal    58       54       60  57.333333
15    Riya    92       90       96  92.666667
16      Om    61       69       65  65.000000
17   Aditi    80       85       83  82.666667
18    Yash    43       49       46  46.000000
19   Sneha    77       73       80  76.666667


In [26]:
top_students = df[df["average"]>=85]
print(top_students[["name","average"]])

      name    average
1     Diya  91.000000
5     Sara  90.333333
7   Ananya  92.000000
13   Priya  88.666667
15    Riya  92.666667


In [27]:
low_attendance = df[df["attendance_percent"]<75]
print(low_attendance[["name","attendance_percent"]])

      name  attendance_percent
4    Rohan                  68
8   Vivaan                  71
12     Dev                  62
18    Yash                  66


In [ ]:
#create filter for students from mathura and print

In [ ]:
#student performance analyser

#1. read the csv
#create average column using math science and english
#result column, is avg is greater than 55 it will be pass otherwise fail
#print class average
#average ka max, average ka min
#Print top student or students.
#Print students with attendance below 75.
#Print students who submitted fewer than 6 assignments

In [28]:
import pandas as pd
import numpy as np


def get_result(avg):
  if avg >=55:
    return "Pass"
  return "fail"


df= pd.read_csv("session4_dummy_students_data.csv")

df["average"] = df[["math", "science", "english"]].mean(axis=1)
df["result"] = df["average"].apply(get_result)


print("Full Data:")
print (df)


print("Class average:", df["average"].mean())
print("Max average:", df["average"].max())
print("Min average:", df["average"].min())



Full Data:
    student_id    name  age     city  math  science  english  \
0          101   Aarav   16   Mumbai    78       84       69   
1          102    Diya   16    Delhi    91       88       94   
2          103   Kabir   17  Mathura    55       61       58   
3          104   Meera   16    Noida    72       79       81   
4          105   Rohan   17   Mumbai    40       52       47   
5          106    Sara   16    Delhi    88       93       90   
6          107  Ishaan   17  Mathura    64       70       66   
7          108  Ananya   16    Noida    95       92       89   
8          109  Vivaan   17   Mumbai    48       57       51   
9          110    Tara   16    Delhi    83       76       85   
10         111   Arjun   17  Mathura    67       63       72   
11         112   Nisha   16    Noida    74       81       79   
12         113     Dev   17   Mumbai    35       45       42   
13         114   Priya   16    Delhi    89       86       91   
14         115   Kunal   17  